<?php
return [
  'available_crypto' => 'BTC, ETH, BCH, LTC, TRX, XMR, BCH, BNB-BSC, BUSD-BSC, CAKE-BSC, DOGE-BSC, DOT-BSC, LTC-BSC, SHIB-BSC, USDT-BSC, USDC-BSC, UNI-BSC, BNB-ERC20, BUSD-ERC20, EURT-ERC20, USDC-ERC20, USDT-ERC20, USDP-ERC20, TUSD-ERC20, DOGE-TRC20, ETH-TRC20, HUSD-TRC20, INRT-TRC20, USDC-TRC20, USDT-TRC20',
  'BTC' => 'btc',
  'ETH' => 'eth',
  'BCH' => 'bch',
  'LTC' => 'ltc',
  'TRX' => 'trx',
  'XMR' => 'xmr',
  'BCH' => 'bch',
  'BNB-BSC' => 'bep20/bnb',
  'BUSD-BSC' => 'bep20/busd',
  'CAKE-BSC' => 'bep20/cake',
  'DOGE-BSC' => 'bep20/doge',
  'DOT-BSC' => 'bep20/dot',
  'LTC-BSC' => 'bep20/ltc',
  'SHIB-BSC' => 'bep20/shib',
  'USDT-BSC' => 'bep20/usdt',
  'USDC-BSC' => 'bep20/usdc',
  'UNI-BSC' => 'bep20/uni',
  'BNB-ERC20' => 'erc20/bnb',
  'BUSD-ERC20' => 'erc20/busd',
  'EURT-ERC20' => 'erc20/eurt',
  'EURT-ERC20' => 'erc20/eurt',
  'USDC-ERC20' => 'erc20/usdc',
  'USDT-ERC20' => 'erc20/usdt',
  'USDP-ERC20' => 'erc20/usdp',
  'TUSD-ERC20' => 'erc20/tusd',
  'DOGE-TRC20' => 'trc20/doge',
  'ETH-TRC20' => 'trc20/eth',
  'HUSD-TRC20' => 'trc20/husd',
  'INRT-TRC20' => 'trc20/inrt',
  'USDC-TRC20' => 'trc20/usdc',
  'USDT-TRC20' => 'trc20/usdt',
];
